version: "2"
services:
  samson:
    # image: zendesk/samson:latest
    build: .
    ports:
      - "9080:9080"
    environment:
      DATABASE_URL: "sqlite3://db/development.sqlite"
      # DATABASE_URL: "root@127.0.0.1:3306"
      # test application samson-compose from some-public-token user (192.168.42.45:9080)
      DEFAULT_URL: "http://deploy.local.restorando.net:9080"
      RAILS_LOG_TO_STDOUT: 1
    env_file: .env
    command: "bash -c 'rake db:setup && puma -C config/puma.rb'"
    tty: true
    stdin_open: true
    volumes:
      - ./app:/app/app/
      - ~/.ssh:/root/.ssh-local:ro

  memcached:
    image: memcached
    ports:
      - "11211:11211"
