version: "2"
services:
  samson:
    # image: zendesk/samson:latest
    build: .
    ports:
      - "9080:9080"
    environment:
      DEFAULT_URL: "http://deploy.local.restorando.net:9080"
      RAILS_LOG_TO_STDOUT: 1
    env_file: .env
    #command: "bash -c 'rake db:setup && puma -C config/puma.rb'"
    command: "bash -c 'rake db:migrate && puma -C config/puma.rb'"
    tty: true
    stdin_open: true
    volumes:
      - ./app:/app/app/
      - ~/.ssh:/root/.ssh-local:ro

  memcached:
    image: memcached
    ports:
      - "11211:11211"
